name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up Git
      run: |
          git config --global user.name "chandrupsj22"
          git config --global user.email "133023965+chandru-kloudping@users.noreply.github.com"
#     - uses: cschleiden/replace-tokens@v1.2
#       with:
#          tokenPrefix: '#{'
#          tokenSuffix: '}#'
#          files: '**/*.txt'
#       env:
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}  
    
    
    
    
    
   
    
