name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up Git
      run: |
          git config --global user.name "chandrupsj22"
          git config --global user.email "133023965+chandru-kloudping@users.noreply.github.com"
    - name: display file.txt
      run: |
        cat /home/runner/work/Gradle-start-project/Gradle-start-project/file.txt
    - name: Replace credentials in file
      run: |
          sed -i "s/{{USERNAME}}/${{ secrets.USERNAME }}/g" /home/runner/work/Gradle-start-project/Gradle-start-project/build.gradle
          sed -i "s/{{PASSWORD}}/${{ secrets.PASSWORD }}/g" /home/runner/work/Gradle-start-project/Gradle-start-project/build.gradle

    - name: Use credentials in workflow
      run: |
          # You can use the replaced credentials here to perform any necessary actions
          echo "Username: ${{ secrets.USERNAME }}"
          echo "Password: ${{ secrets.PASSWORD }}"
          echo " content in Gradle"
          cat /home/runner/work/Gradle-start-project/Gradle-start-project/build.gradle
 
    - name: Display File Content
      run: cat /home/runner/work/Gradle-start-project/Gradle-start-project/file.txt
#     - uses: cschleiden/replace-tokens@v1.2
#       with:
#          tokenPrefix: '#{'
#          tokenSuffix: '}#'
#          files: '**/*.txt'
#       env:
#           username: ${{ secrets.USERNAME }}
#           password: ${{ secrets.PASSWORD }}  
    - name: Run Gradle Versions Check
      run: ./gradlew dependencyUpdates -Drevision=release
    
    
    
    
    
   
    
