name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Set up Git
      run: |
          git config --global user.name "chandrupsj22"
          git config --global user.email "133023965+chandru-kloudping@users.noreply.github.com"
    - name: Determine Latest Tag
      id: latest_tag
      run: echo ::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)
   
    - name: Increment version
      id: increment_version
      run: |
          # Extract the current version
          version=$(echo "${{ steps.get_latest_tag.outputs.tag }}" | sed -E 's/^v([0-9]+)\.([0-9]+)$/\1.\2/')

          # Increment the minor version
          new_version=$(echo "${version}" | awk -F. '{$2 = $2 + 1; print}' OFS=".")

          # Set the new version as an output
          echo ::set-output name=new_version::"${new_version}"

    - name: Create new tag
      id: create_tag
      run: |
          # Create a new tag with the incremented version
          git tag -a "v${{ steps.increment_version.outputs.new_version }}" -m "Incremented version"

          # Push the new tag
          git push origin "v${{ steps.increment_version.outputs.new_version }}"
                
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/
    - name: List Artifacts
      run: |
        echo "Build Artifacts:"
        ls ${{ steps.view.outputs.artifact_folder }}
    - name: Display .jar File Name
      run: |
        echo "The .jar file name is: $(find build/ -name '*.jar')"
    - name: Download and List Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: build-artifacts
    - name: List Artifact Contents
      run: ls -R build-artifacts/distributions
